
export const routes: RoutesType = {
    SPLASH: "SPLASH",
    WELCOME: "WELCOME",
    WELCOMETWO: "WELCOMETWO",
    RECRUITERPROFILE: "RECRUITERPROFILE",
    CONTACT: "CONTACT",
    CHAT: "CHAT",
    LOGIN: "LOGIN",
    BLOG: "BLOG",
    HOME: "HOME",
    MESSAGE: "MESSAGE",
    PAYMENTHISTORY: "PAYMENTHISTORY",
    RECRUITERHOME: "RECRUITERHOME",
    PROJECT: "PROJECT",
    BLOGPAGE: "BLOGPAGE",
    NOTIFICATION: "NOTIFICATION",
    SIGNUP: "SIGNUP",
    FORGOTPASSWORD: "FORGOTPASSWORD",
    SUGGESTEDJOB: "SUGGESTEDJOB",
    SEARCH: "SEARCH",
    JOBDETAIL: "JOBDETAIL",
    OPENJOBS: "OPENJOBS",
    COMPANY: "COMPANY",
    COMPANYDETAILS: "COMPANYDETAILS",
    PROFILE: "PROFILE",
    ACCOUNT: "ACCOUNT",
    ADDJOB: "ADDJOB",
    PERSONALINFO: "PERSONALINFO",
    WORKEXPERIENCE: "WORKEXPERIENCE",
    WORKEXPERIENCEFORM: "WORKEXPERIENCEFORM",
    CANDIDATEPROFILE: "CANDIDATEPROFILE",
    EDUCATION: "EDUCATION",
    EDUCATIONFORM: "EDUCATIONFORM",
    CV: "CV",
    CVADD: "CVADD",
    RECENTJOB: "RECENTJOB",
    APPLYJOB: "APPLYJOB",
    PROJECTFORM: "PROJECTFORM",
    APPLY: "APPLY",
    SKILL: "SKILL",
    SKILLFORM: "SKILLFORM",
    LANGUAGE: "LANGUAGE",
    LANGUAGEFORM: "LANGUAGEFORM",
    ACTIVECANDIDATE: "ACTIVECANDIDATE",
    BROWSER: "BROWSER",



}
export default interface RoutesType {
    SPLASH: "SPLASH",
    EDUCATION: "EDUCATION",
    BLOGPAGE: "BLOGPAGE",
    EDUCATIONFORM: "EDUCATIONFORM",
    NOTIFICATION: "NOTIFICATION",
    ACCOUNT: "ACCOUNT",
    PAYMENTHISTORY: "PAYMENTHISTORY",
    MESSAGE: "MESSAGE",
    CONTACT: "CONTACT",
    BLOG: "BLOG",

    LANGUAGE: "LANGUAGE",
    LANGUAGEFORM: "LANGUAGEFORM",
    CVADD: "CVADD",
    RECENTJOB: "RECENTJOB",
    ADDJOB: "ADDJOB",
    APPLYJOB: "APPLYJOB",
    CANDIDATEPROFILE: "CANDIDATEPROFILE",
    RECRUITERHOME: "RECRUITERHOME",

    PROJECT: "PROJECT",
    SKILL: "SKILL",
    SKILLFORM: "SKILLFORM",
    CV: "CV",
    CHAT: "CHAT",
    COMPANYDETAILS: "COMPANYDETAILS",
    PROFILE: "PROFILE",
    PERSONALINFO: "PERSONALINFO",
    RECRUITERPROFILE: "RECRUITERPROFILE",
    WORKEXPERIENCEFORM: "WORKEXPERIENCEFORM",
    WORKEXPERIENCE: "WORKEXPERIENCE",
    SUGGESTEDJOB: "SUGGESTEDJOB",
    WELCOME: "WELCOME",
    OPENJOBS: "OPENJOBS",
    WELCOMETWO: "WELCOMETWO",
    JOBDETAIL: "JOBDETAIL",
    COMPANY: "COMPANY",
    LOGIN: "LOGIN",
    HOME: "HOME",
    SIGNUP: "SIGNUP",
    FORGOTPASSWORD: "FORGOTPASSWORD",
    SEARCH: "SEARCH",
    PROJECTFORM: "PROJECTFORM",
    APPLY: "APPLY",
    ACTIVECANDIDATE: "ACTIVECANDIDATE",
    BROWSER: "BROWSER",



}
export const COUNTRIES = [
    { id: 1, name: "Afghanistan", countryCode: "+93", flag: "🇦🇫" },
    { id: 2, name: "Albania", countryCode: "+355", flag: "🇦🇱" },
    { id: 3, name: "Algeria", countryCode: "+213", flag: "🇩🇿" },
    { id: 4, name: "Andorra", countryCode: "+376", flag: "🇦🇩" },
    { id: 5, name: "Angola", countryCode: "+244", flag: "🇦🇴" },
    { id: 6, name: "Antigua and Barbuda", countryCode: "+1268", flag: "🇦🇬" },
    { id: 7, name: "Argentina", countryCode: "+54", flag: "🇦🇷" },
    { id: 8, name: "Armenia", countryCode: "+374", flag: "🇦🇲" },
    { id: 9, name: "Australia", countryCode: "+61", flag: "🇦🇺" },
    { id: 10, name: "Austria", countryCode: "+43", flag: "🇦🇹" },
    { id: 11, name: "Azerbaijan", countryCode: "+994", flag: "🇦🇿" },
    { id: 12, name: "Bahamas", countryCode: "+1242", flag: "🇧🇸" },
    { id: 13, name: "Bahrain", countryCode: "+973", flag: "🇧🇭" },
    { id: 14, name: "Bangladesh", countryCode: "+880", flag: "🇧🇩" },
    { id: 15, name: "Barbados", countryCode: "+1246", flag: "🇧🇧" },
    { id: 16, name: "Belarus", countryCode: "+375", flag: "🇧🇾" },
    { id: 17, name: "Belgium", countryCode: "+32", flag: "🇧🇪" },
    { id: 18, name: "Belize", countryCode: "+501", flag: "🇧🇿" },
    { id: 19, name: "Benin", countryCode: "+229", flag: "🇧🇯" },
    { id: 20, name: "Bhutan", countryCode: "+975", flag: "🇧🇹" },
    { id: 21, name: "Bolivia", countryCode: "+591", flag: "🇧🇴" },
    { id: 22, name: "Bosnia and Herzegovina", countryCode: "+387", flag: "🇧🇦" },
    { id: 23, name: "Botswana", countryCode: "+267", flag: "🇧🇼" },
    { id: 24, name: "Brazil", countryCode: "+55", flag: "🇧🇷" },
    { id: 25, name: "Brunei", countryCode: "+673", flag: "🇧🇳" },
    { id: 26, name: "Bulgaria", countryCode: "+359", flag: "🇧🇬" },
    { id: 27, name: "Burkina Faso", countryCode: "+226", flag: "🇧🇫" },
    { id: 28, name: "Burundi", countryCode: "+257", flag: "🇧🇮" },
    { id: 29, name: "Cambodia", countryCode: "+855", flag: "🇰🇭" },
    { id: 30, name: "Cameroon", countryCode: "+237", flag: "🇨🇲" },
    { id: 31, name: "Canada", countryCode: "+1", flag: "🇨🇦" },
    { id: 32, name: "Central African Republic", countryCode: "+236", flag: "🇨🇫" },
    { id: 33, name: "Chad", countryCode: "+235", flag: "🇹🇩" },
    { id: 34, name: "Chile", countryCode: "+56", flag: "🇨🇱" },
    { id: 35, name: "China", countryCode: "+86", flag: "🇨🇳" },
    { id: 36, name: "Colombia", countryCode: "+57", flag: "🇨🇴" },
    { id: 37, name: "Comoros", countryCode: "+269", flag: "🇰🇲" },
    { id: 38, name: "Congo", countryCode: "+242", flag: "🇨🇬" },
    { id: 39, name: "Costa Rica", countryCode: "+506", flag: "🇨🇷" },
    { id: 40, name: "Croatia", countryCode: "+385", flag: "🇭🇷" },
    { id: 41, name: "Cuba", countryCode: "+53", flag: "🇨🇺" },
    { id: 42, name: "Cyprus", countryCode: "+357", flag: "🇨🇾" },
    { id: 43, name: "Czech Republic", countryCode: "+420", flag: "🇨🇿" },
    { id: 44, name: "Denmark", countryCode: "+45", flag: "🇩🇰" },
    { id: 45, name: "Djibouti", countryCode: "+253", flag: "🇩🇯" },
    { id: 46, name: "Dominica", countryCode: "+1767", flag: "🇩🇲" },
    { id: 47, name: "Dominican Republic", countryCode: "+1809", flag: "🇩🇴" },
    { id: 48, name: "Ecuador", countryCode: "+593", flag: "🇪🇨" },
    { id: 49, name: "Egypt", countryCode: "+20", flag: "🇪🇬" },
    { id: 50, name: "El Salvador", countryCode: "+503", flag: "🇸🇻" },
    { id: 51, name: "Equatorial Guinea", countryCode: "+240", flag: "🇬🇶" },
    { id: 52, name: "Eritrea", countryCode: "+291", flag: "🇪🇷" },
    { id: 53, name: "Estonia", countryCode: "+372", flag: "🇪🇪" },
    { id: 54, name: "Eswatini", countryCode: "+268", flag: "🇸🇿" },
    { id: 55, name: "Ethiopia", countryCode: "+251", flag: "🇪🇹" },
    { id: 56, name: "Fiji", countryCode: "+679", flag: "🇫🇯" },
    { id: 57, name: "Finland", countryCode: "+358", flag: "🇫🇮" },
    { id: 58, name: "France", countryCode: "+33", flag: "🇫🇷" },
    { id: 59, name: "Gabon", countryCode: "+241", flag: "🇬🇦" },
    { id: 60, name: "Gambia", countryCode: "+220", flag: "🇬🇲" },
    { id: 61, name: "Georgia", countryCode: "+995", flag: "🇬🇪" },
    { id: 62, name: "Germany", countryCode: "+49", flag: "🇩🇪" },
    { id: 63, name: "Ghana", countryCode: "+233", flag: "🇬🇭" },
    { id: 64, name: "Greece", countryCode: "+30", flag: "🇬🇷" },
    { id: 65, name: "Grenada", countryCode: "+1473", flag: "🇬🇩" },
    { id: 66, name: "Guatemala", countryCode: "+502", flag: "🇬🇹" },
    { id: 67, name: "Guinea", countryCode: "+224", flag: "🇬🇳" },
    { id: 68, name: "Guyana", countryCode: "+592", flag: "🇬🇾" },
    { id: 69, name: "Haiti", countryCode: "+509", flag: "🇭🇹" },
    { id: 70, name: "Honduras", countryCode: "+504", flag: "🇭🇳" },
    { id: 71, name: "Hungary", countryCode: "+36", flag: "🇭🇺" },
    { id: 72, name: "Iceland", countryCode: "+354", flag: "🇮🇸" },
    { id: 73, name: "India", countryCode: "+91", flag: "🇮🇳" },
    { id: 74, name: "Indonesia", countryCode: "+62", flag: "🇮🇩" },
    { id: 75, name: "Iran", countryCode: "+98", flag: "🇮🇷" },
    { id: 76, name: "Iraq", countryCode: "+964", flag: "🇮🇶" },
    { id: 77, name: "Ireland", countryCode: "+353", flag: "🇮🇪" },
    { id: 78, name: "Israel", countryCode: "+972", flag: "🇮🇱" },
    { id: 79, name: "Italy", countryCode: "+39", flag: "🇮🇹" },
    { id: 80, name: "Jamaica", countryCode: "+1876", flag: "🇯🇲" },
    { id: 81, name: "Japan", countryCode: "+81", flag: "🇯🇵" },
    { id: 82, name: "Jordan", countryCode: "+962", flag: "🇯🇴" },
    { id: 83, name: "Kazakhstan", countryCode: "+7", flag: "🇰🇿" },
    { id: 84, name: "Kenya", countryCode: "+254", flag: "🇰🇪" },
    { id: 85, name: "Kiribati", countryCode: "+686", flag: "🇰🇮" },
    { id: 86, name: "Kuwait", countryCode: "+965", flag: "🇰🇼" },
    { id: 87, name: "Kyrgyzstan", countryCode: "+996", flag: "🇰🇬" },
    { id: 88, name: "Laos", countryCode: "+856", flag: "🇱🇦" },
    { id: 89, name: "Latvia", countryCode: "+371", flag: "🇱🇻" },
    { id: 90, name: "Lebanon", countryCode: "+961", flag: "🇱🇧" },
    { id: 91, name: "Lesotho", countryCode: "+266", flag: "🇱🇸" },
    { id: 92, name: "Liberia", countryCode: "+231", flag: "🇱🇷" },
    { id: 93, name: "Libya", countryCode: "+218", flag: "🇱🇾" },
    { id: 94, name: "Liechtenstein", countryCode: "+423", flag: "🇱🇮" },
    { id: 95, name: "Lithuania", countryCode: "+370", flag: "🇱🇹" },
    { id: 96, name: "Luxembourg", countryCode: "+352", flag: "🇱🇺" },
    { id: 97, name: "Madagascar", countryCode: "+261", flag: "🇲🇬" },
    { id: 98, name: "Malawi", countryCode: "+265", flag: "🇲🇼" },
    { id: 99, name: "Malaysia", countryCode: "+60", flag: "🇲🇾" },
    { id: 100, name: "Maldives", countryCode: "+960", flag: "🇲🇻" },
    { id: 101, name: "Mali", countryCode: "+223", flag: "🇲🇱" },
    { id: 102, name: "Malta", countryCode: "+356", flag: "🇲🇹" },
    { id: 103, name: "Mauritania", countryCode: "+222", flag: "🇲🇷" },
    { id: 104, name: "Mauritius", countryCode: "+230", flag: "🇲🇺" },
    { id: 105, name: "Mexico", countryCode: "+52", flag: "🇲🇽" },
    { id: 106, name: "Moldova", countryCode: "+373", flag: "🇲🇩" },
    { id: 107, name: "Monaco", countryCode: "+377", flag: "🇲🇨" },
    { id: 108, name: "Mongolia", countryCode: "+976", flag: "🇲🇳" },
    { id: 109, name: "Montenegro", countryCode: "+382", flag: "🇲🇪" },
    { id: 110, name: "Morocco", countryCode: "+212", flag: "🇲🇦" },
    { id: 111, name: "Mozambique", countryCode: "+258", flag: "🇲🇿" },
    { id: 112, name: "Myanmar", countryCode: "+95", flag: "🇲🇲" },
    { id: 113, name: "Namibia", countryCode: "+264", flag: "🇳🇦" },
    { id: 114, name: "Nauru", countryCode: "+674", flag: "🇳🇷" },
    { id: 115, name: "Nepal", countryCode: "+977", flag: "🇳🇵" },
    { id: 116, name: "Netherlands", countryCode: "+31", flag: "🇳🇱" },
    { id: 117, name: "New Zealand", countryCode: "+64", flag: "🇳🇿" },
    { id: 118, name: "Nicaragua", countryCode: "+505", flag: "🇳🇮" },
    { id: 119, name: "Niger", countryCode: "+227", flag: "🇳🇪" },
    { id: 120, name: "Nigeria", countryCode: "+234", flag: "🇳🇬" },
    { id: 121, name: "North Korea", countryCode: "+850", flag: "🇰🇵" },
    { id: 122, name: "North Macedonia", countryCode: "+389", flag: "🇲🇰" },
    { id: 123, name: "Norway", countryCode: "+47", flag: "🇳🇴" },
    { id: 124, name: "Oman", countryCode: "+968", flag: "🇴🇲" },
    { id: 125, name: "Pakistan", countryCode: "+92", flag: "🇵🇰" },
    { id: 126, name: "Panama", countryCode: "+507", flag: "🇵🇦" },
    { id: 127, name: "Papua New Guinea", countryCode: "+675", flag: "🇵🇬" },
    { id: 128, name: "Paraguay", countryCode: "+595", flag: "🇵🇾" },
    { id: 129, name: "Peru", countryCode: "+51", flag: "🇵🇪" },
    { id: 130, name: "Philippines", countryCode: "+63", flag: "🇵🇭" },
    { id: 131, name: "Poland", countryCode: "+48", flag: "🇵🇱" },
    { id: 132, name: "Portugal", countryCode: "+351", flag: "🇵🇹" },
    { id: 133, name: "Qatar", countryCode: "+974", flag: "🇶🇦" },
    { id: 134, name: "Romania", countryCode: "+40", flag: "🇷🇴" },
    { id: 135, name: "Russia", countryCode: "+7", flag: "🇷🇺" },
    { id: 136, name: "Rwanda", countryCode: "+250", flag: "🇷🇼" },
    { id: 137, name: "Saint Kitts and Nevis", countryCode: "+1869", flag: "🇰🇳" },
    { id: 138, name: "Saint Lucia", countryCode: "+1758", flag: "🇱🇨" },
    { id: 139, name: "Saint Vincent and the Grenadines", countryCode: "+1784", flag: "🇻🇨" },
    { id: 140, name: "Samoa", countryCode: "+685", flag: "🇼🇸" },
    { id: 141, name: "San Marino", countryCode: "+378", flag: "🇸🇲" },
    { id: 142, name: "Sao Tome and Principe", countryCode: "+239", flag: "🇸🇹" },
    { id: 143, name: "Saudi Arabia", countryCode: "+966", flag: "🇸🇦" },
    { id: 144, name: "Senegal", countryCode: "+221", flag: "🇸🇳" },
    { id: 145, name: "Serbia", countryCode: "+381", flag: "🇷🇸" },
    { id: 146, name: "Seychelles", countryCode: "+248", flag: "🇸🇨" },
    { id: 147, name: "Sierra Leone", countryCode: "+232", flag: "🇸🇱" },
    { id: 148, name: "Singapore", countryCode: "+65", flag: "🇸🇬" },
    { id: 149, name: "Slovakia", countryCode: "+421", flag: "🇸🇰" },
    { id: 150, name: "Slovenia", countryCode: "+386", flag: "🇸🇮" },
    { id: 151, name: "Solomon Islands", countryCode: "+677", flag: "🇸🇧" },
    { id: 152, name: "Somalia", countryCode: "+252", flag: "🇸🇴" },
    { id: 153, name: "South Africa", countryCode: "+27", flag: "🇿🇦" },
    { id: 154, name: "South Korea", countryCode: "+82", flag: "🇰🇷" },
    { id: 155, name: "South Sudan", countryCode: "+211", flag: "🇸🇸" },
    { id: 156, name: "Spain", countryCode: "+34", flag: "🇪🇸" },
    { id: 157, name: "Sri Lanka", countryCode: "+94", flag: "🇱🇰" },
    { id: 158, name: "Sudan", countryCode: "+249", flag: "🇸🇩" },
    { id: 159, name: "Suriname", countryCode: "+597", flag: "🇸🇷" },
    { id: 160, name: "Sweden", countryCode: "+46", flag: "🇸🇪" },
    { id: 161, name: "Switzerland", countryCode: "+41", flag: "🇨🇭" },
    { id: 162, name: "Syria", countryCode: "+963", flag: "🇸🇾" },
    { id: 163, name: "Taiwan", countryCode: "+886", flag: "🇹🇼" },
    { id: 164, name: "Tajikistan", countryCode: "+992", flag: "🇹🇯" },
    { id: 165, name: "Tanzania", countryCode: "+255", flag: "🇹🇿" },
    { id: 166, name: "Thailand", countryCode: "+66", flag: "🇹🇭" },
    { id: 167, name: "Togo", countryCode: "+228", flag: "🇹🇬" },
    { id: 168, name: "Tonga", countryCode: "+676", flag: "🇹🇴" },
    { id: 169, name: "Trinidad and Tobago", countryCode: "+1868", flag: "🇹🇹" },
    { id: 170, name: "Tunisia", countryCode: "+216", flag: "🇹🇳" },
    { id: 171, name: "Turkey", countryCode: "+90", flag: "🇹🇷" },
    { id: 172, name: "Turkmenistan", countryCode: "+993", flag: "🇹🇲" },
    { id: 173, name: "Tuvalu", countryCode: "+688", flag: "🇹🇻" },
    { id: 174, name: "Uganda", countryCode: "+256", flag: "🇺🇬" },
    { id: 175, name: "Ukraine", countryCode: "+380", flag: "🇺🇦" },
    { id: 176, name: "United Arab Emirates", countryCode: "+971", flag: "🇦🇪" },
    { id: 177, name: "United Kingdom", countryCode: "+44", flag: "🇬🇧" },
    { id: 178, name: "United States", countryCode: "+1", flag: "🇺🇸" },
    { id: 179, name: "Uruguay", countryCode: "+598", flag: "🇺🇾" },
    { id: 180, name: "Uzbekistan", countryCode: "+998", flag: "🇺🇿" },
    { id: 181, name: "Vanuatu", countryCode: "+678", flag: "🇻🇺" },
    { id: 182, name: "Vatican City", countryCode: "+379", flag: "" },
    { id: 183, name: "Venezuela", countryCode: "+58", flag: "🇻🇪" },
    { id: 184, name: "Vietnam", countryCode: "+84", flag: "🇻🇳" },
    { id: 185, name: "Yemen", countryCode: "+967", flag: "🇾🇪" },
    { id: 186, name: "Zambia", countryCode: "+260", flag: "🇿🇲" },
    { id: 187, name: "Zimbabwe", countryCode: "+263", flag: "🇿🇼" },
    { id: 188, name: "Kosovo", countryCode: "+383", flag: "🇽🇰" },
    { id: 189, name: "Palestine", countryCode: "+970", flag: "🇵🇸" },
    { id: 190, name: "Monaco", countryCode: "+377", flag: "🇲🇨" },
    { id: 191, name: "Nicaragua", countryCode: "+505", flag: "🇳🇮" },
    { id: 192, name: "Moldova", countryCode: "+373", flag: "🇲🇩" },
    { id: 193, name: "Micronesia", countryCode: "+691", flag: "🇫🇲" },
];

export const HOST = `192.168.1.2`


export const API_URL = `https://searchtalents.co/api/v1`



