# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
platform :ios, min_ios_version_supported
prepare_react_native_project!
# pod 'Firebase', :modular_headers => true

# pod 'FirebaseCore', :modular_headers => true
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
  $RNFirebaseAsStaticFramework = true
end

target 'SearchTalent' do
  ENV['RCT_NEW_ARCH_ENABLED'] = '0'
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Fix for Xcode compatibility
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'

      end
    end
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |cfg|
          cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -w -DFMT_COMPILE_TIME_CHECKS=0'
          cfg.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'  # downgrade from c++20
        end
      end

      # Fix for Xcode 26: std::thread is no longer pulled in transitively by libc++
      # Force-include <thread> for React-hermes to fix HermesExecutorFactory.cpp errors
      if target.name == 'React-hermes'
        target.build_configurations.each do |cfg|
          cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -w -include thread'
        end
      end

      target.build_configurations.each do |cfg|
        cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        cfg.build_settings['WARNING_CFLAGS'] = '-w'
        cfg.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        cfg.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -w'
        cfg.build_settings['OTHER_CFLAGS'] = '$(inherited) -w'
      end
    end
  end
end
