// export {default as Explore} from './Explore/Explore'
// export {default as Bookmark} from './Bookmark/Bookmark'
// export {default as BlogInfo} from './BlogInfo/BlogInfo'
// export {default as Tranding} from './Tranding/Tranding'
// export {default as Notification} from './Notification/Notification'
// export {default as Search} from "./Search/Search"
// export {default as Page} from "./Page/Page"

// export {default as OtpVerification} from "./Auth/OtpVerification"
// export {default as ResetPassword} from "./Auth/ResetPassword"
// export {default as Country} from "./Country/Country"
// export {default as Topic} from "./Topic/Topic"
// export {default as Profile} from "./Profile/Profile"

// export {default as Setting} from "./Setting/Setting"
// export {default as NotificationSetting} from "./Setting/Notification"
// export {default as Security} from "./Setting/Security"
// export {default as ChangePassword} from "./Setting/ChangePassword"
// export {default as ChangeEmail} from "./Setting/ChangeEmail"
// export {default as News} from "./New/New"
// export {default as PostDetails} from "./Post/PostDetails"
// export {default as EditProfileScreen} from "../pages/EditProfileScreen/EditProfileScreen"
// export {default as WebViewScreen} from "./WebViewScreen/WebViewScreen"
// export {default as Follwing} from "./Follwing/Follwing"
// export {default as Help} from "./Help/Help"
// export {default as ContactSupport} from "./ContactSupport/ContactSupport"
// export {default as Faqs} from "./Faqs/Faqs"
// export {default as VerificationProfileTick} from "./VerificationProfileTick/VerificationProfileTick"
// export {default as BlockedUsers} from "./BlockedUsers/BlockedUsers"
// export {default as AddStory} from "./AddStory/AddStory"
// export {default as PostSearch} from "./Search/PostSearch"
// export {default as ReelsPage} from "./ReelsPage/ReelsPage"
// export {default as ViewAllStorys} from "./ViewAllStorys/ViewAllStorys"

// export {default as AddStory} from "./AddStory/AddStory"
// export {default as StoryCreator} from "./AddStory/StoryCreator"

export { default as Splash } from "./Splash/Splash"
export { default as Welcome } from "./Welcome/Welcome"
export { default as WelcomeTwo } from "./Welcome/WelcomeTwo"
export {default as Login} from "./Auth/Login"
export {default as Home} from './Home/Home'
export {default as Signup} from "./Auth/Signup"
export {default as ForgotPassword} from "./Auth/ForgotPassword"
export {default as Setting} from "./Setting/Setting"
export {default as Chat} from "./Chat/Chat"
export {default as Search} from "./Search/Search"
export {default as Jobdetail} from "./Jobdetail/Jobdetail"
export {default as Company} from "./Company/Company"
export {default as CompanyDetails} from "./CompanyDetails/CompanyDetails"
export {default as SuggestedJob} from "./SuggestedJob/SuggestedJob"
export {default as Profile} from "./Profile/Profile"
export {default as PersonalInfo} from "./PersonalInfo/PersonalInfo"
export {default as WorkExperience} from "./PersonalInfo/WorkExperience"
export {default as WorkExperienceForm} from "./PersonalInfo/WorkExperienceForm"
export {default as Education} from "./PersonalInfo/Education"
export {default as Project} from "./PersonalInfo/Project"
export {default as CV} from "./PersonalInfo/CV"
export {default as RecentJob} from "./RecentJob/RecentJob"
export {default as ApplyJob} from "./Applyjob/ApplyJob"
export {default as ProjectForm} from "./PersonalInfo/ProjectForm"
export {default as Skill} from "./PersonalInfo/Skill"
export {default as SkillAdd} from "./PersonalInfo/SkillAdd"
export {default as Language} from "./PersonalInfo/Language"
export {default as LanguageForm} from "./PersonalInfo/LanguageForm"
export {default as Apply} from "./Apply/ApplyJob"
export {default as Notification} from "./Notification/Notification"

