export default {
    activeApplication: require('./Icon/active-application.png'),
    application: require('./Icon/application.png'),
    activeCompany: require('./Icon/active-company.png'),
    company: require('./Icon/company.png'),
    home: require('./Icon/home.png'),
    activeHome: require('./Icon/active-home.png'),
    activeProfile: require('./Icon/active-profile.png'),
    profile: require('./Icon/profile.png'),
    logo: require('./Icon/logo.png'),
    bookmark: require('./Icon/bookmark.png'),
    backIcon: require('./Icon/backIcon.png'),
    search: require('./Icon/search.png'),
    history: require('./Icon/history.png'),
    cross: require('./Icon/cross.png'),
    box: require('./Icon/box.png'),
    location: require('./Icon/location.png'),
    star: require('./Icon/star.png'),
    bag: require('./Icon/bag.png'),
    circle: require('./Icon/circle.png'),
    verify: require('./Icon/verify.png'),
    company2: require('./Icon/company2.png'),
    users: require('./Icon/users.png'),
    bag2: require('./Icon/bag2.png'),
    camera: require('./Icon/camera.png'),
    notification: require('./Icon/notification.png'),
    calendar: require('./Icon/calendar.png'),
    clock: require('./Icon/clock.png'),
    threeDot: require('./Icon/threeDot.png'),
    download: require('./Icon/download.png'),
    delete: require('./Icon/delete.png'),
    calender2: require('./Icon/calender2.png'),
    company3: require('./Icon/company3.png'),
    location2: require('./Icon/location2.png'),
    edit: require('./Icon/edit.png'),
    education: require('./Icon/education.png'),
    camera2: require('./Icon/camera2.png'),
    myJob: require('./Icon/myJob.png'),
    clock2: require('./Icon/clock2.png'),
    candidate: require('./Icon/candidate.png'),
    activeCandidate: require('./Icon/activeCandidate.png'),
    addJob: require('./Icon/addJob.png'),
    activeAddJob: require('./Icon/activeAddJob.png'),
    check: require('./Icon/check.png'),
    chat: require('./Icon/chat.png'),
    chat2: require('./Icon/chat2.png'),
    angle: require('./Icon/angle.png'),


    // images
    banner: require('./images/banner.png'),
    homeSearch: require('./images/homeSearch.png'),
    jobtype1: require('./images/jobtype1.png'),
    jobtype2: require('./images/jobtype2.png'),
    jobtype3: require('./images/jobtype3.png'),
    jobtype4: require('./images/jobtype4.png'),
    filter: require('./images/filter.png'),
    googleLogo: require('./images/googleLogo.png'),
    image1: require('./images/image1.png'),
    imageInput: require('./images/imageInput.png'),
    profileUpdateButton: require('./images/profileUpdateButton.png'),
    workExperience: require('./images/workExperience.png'),
    educationImage: require('./images/educationImage.png'),
    success: require('./images/success.png'),
    notificationEmptyImage: require('./images/notification.png'),
    homeBackGround: require('./images/Home.png'),
    transparent: require('./images/homeBG.png'),
    homeText: require('./images/homeText.png'),
    button: require('./images/button.png'),
    recruterBanner: require('./images/recruterBanner.png'),
    recruterHomeText: require('./images/recruterHomeText.png'),


// dummy
    companyDummy: require('./Icon/company-dummy.png'),
}
export const Fonts = {
    GilroyBold: 'Gilroy-Bold',
    GilroyLight: 'Gilroy-Light',
    GilroyMedium: 'Gilroy-Medium',
    GilroyRegular: 'Gilroy-Regular',
    GilroySemiBold: 'Gilroy-SemiBold',
}